CREATE TABLE candidate_memory_claims (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id VARCHAR(64) NOT NULL,
  claim_type VARCHAR(30) NOT NULL,
  skill_id VARCHAR(64) NOT NULL,
  focus_id VARCHAR(64) NOT NULL,
  verification_status VARCHAR(20) NOT NULL,
  source_session_id VARCHAR(36) NOT NULL,
  source_turn_index INTEGER NOT NULL,
  observed_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_candidate_memory_claim_session
    FOREIGN KEY (source_session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_candidate_memory_claim_turn
    FOREIGN KEY (source_session_id, source_turn_index)
    REFERENCES agent_turns(session_id, turn_index),
  CONSTRAINT uk_candidate_memory_claim_source
    UNIQUE (
      source_session_id,
      source_turn_index,
      claim_type,
      skill_id,
      focus_id
    ),
  CONSTRAINT candidate_memory_claim_type_check
    CHECK (claim_type IN ('SKILL', 'PROJECT_EXPERIENCE')),
  CONSTRAINT candidate_memory_claim_verification_check
    CHECK (verification_status = 'UNVERIFIED')
);

CREATE INDEX idx_candidate_memory_claims_candidate_observed
  ON candidate_memory_claims (candidate_id, observed_at DESC);
