ALTER TABLE agent_sessions
  ADD COLUMN tenant_id VARCHAR(64);

CREATE INDEX idx_agent_sessions_tenant_id
  ON agent_sessions (tenant_id, id);

CREATE TABLE adaptive_mcp_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  credential_id VARCHAR(64) NOT NULL,
  tool_name VARCHAR(80) NOT NULL,
  resource_id VARCHAR(64),
  outcome VARCHAR(20) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT adaptive_mcp_audit_outcome_check
    CHECK (outcome IN ('SUCCEEDED', 'FORBIDDEN', 'NOT_FOUND'))
);

CREATE INDEX idx_adaptive_mcp_audits_tenant_created
  ON adaptive_mcp_audits (tenant_id, created_at DESC);
