ALTER TABLE candidate_memory_episode_facts ADD COLUMN enrichment_execution_token VARCHAR(36);
ALTER TABLE candidate_memory_episode_facts ADD COLUMN enrichment_lease_until TIMESTAMP;
ALTER TABLE candidate_memory_episode_facts ADD COLUMN enrichment_attempts INTEGER NOT NULL DEFAULT 0;
CREATE TABLE candidate_memory_observation_revisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  episode_id BIGINT NOT NULL REFERENCES candidate_memory_episode_facts(id),
  revision BIGINT NOT NULL,
  tenant_id VARCHAR(64), candidate_id VARCHAR(64) NOT NULL,
  session_id VARCHAR(36) NOT NULL, session_mode VARCHAR(16) NOT NULL,
  skill_id VARCHAR(64) NOT NULL, focus_id VARCHAR(64) NOT NULL,
  capability_key VARCHAR(64) NOT NULL, objective TEXT NOT NULL,
  opportunity_key VARCHAR(100) NOT NULL, independent BOOLEAN NOT NULL,
  retracted BOOLEAN NOT NULL, reason TEXT, input_fingerprint VARCHAR(64) NOT NULL,
  rules_version VARCHAR(40) NOT NULL, provider VARCHAR(160),
  source_context_json TEXT NOT NULL, observation_json TEXT NOT NULL, summary TEXT NOT NULL, created_at TIMESTAMP NOT NULL,
  UNIQUE (episode_id, revision)
);
CREATE INDEX idx_memory_observation_owner_topic ON candidate_memory_observation_revisions(candidate_id,tenant_id,skill_id,focus_id,episode_id,revision);
ALTER TABLE agent_turns ADD COLUMN adopted_memory_refs TEXT;
