CREATE TABLE agent_sessions (
  id VARCHAR(36) PRIMARY KEY,
  runtime_version VARCHAR(32) NOT NULL,
  jd TEXT NOT NULL,
  resume TEXT NOT NULL,
  mode VARCHAR(20) NOT NULL,
  candidate_level VARCHAR(20) NOT NULL,
  practice_scope_json TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  current_turn INTEGER NOT NULL,
  max_turns INTEGER NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  completed_at TIMESTAMP(6),
  CONSTRAINT agent_sessions_status_check
    CHECK (status IN ('CREATED', 'IN_PROGRESS', 'COMPLETED')),
  CONSTRAINT agent_sessions_mode_check
    CHECK (mode IN ('EVALUATION', 'PRACTICE')),
  CONSTRAINT agent_sessions_candidate_level_check
    CHECK (candidate_level IN ('INTERN', 'CAMPUS', 'EXPERIENCED')),
  CONSTRAINT agent_sessions_turn_bounds_check
    CHECK (current_turn >= 0 AND current_turn <= max_turns),
  CONSTRAINT agent_sessions_max_turns_check
    CHECK (max_turns BETWEEN 1 AND 12),
  CONSTRAINT agent_sessions_practice_scope_check
    CHECK (
      (mode = 'EVALUATION' AND practice_scope_json = '[]')
      OR (mode = 'PRACTICE' AND practice_scope_json <> '[]')
    )
);

CREATE INDEX idx_agent_sessions_status_created
  ON agent_sessions (status, created_at);

CREATE TABLE agent_turns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  turn_index INTEGER NOT NULL,
  question TEXT NOT NULL,
  answer TEXT,
  response_type VARCHAR(20),
  response_content TEXT,
  decision_reason VARCHAR(500),
  created_at TIMESTAMP(6) NOT NULL,
  answered_at TIMESTAMP(6),
  CONSTRAINT fk_agent_turn_session
    FOREIGN KEY (session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT uk_agent_turn_session_index
    UNIQUE (session_id, turn_index),
  CONSTRAINT agent_turn_response_type_check
    CHECK (response_type IS NULL OR response_type IN ('ASK', 'FINISH'))
);

CREATE INDEX idx_agent_turns_session_index
  ON agent_turns (session_id, turn_index);
