CREATE TABLE algorithm_problems (
  id VARCHAR(64) PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  statement TEXT NOT NULL,
  difficulty VARCHAR(16) NOT NULL,
  tags TEXT NOT NULL,
  sample_cases_ref VARCHAR(512) NOT NULL,
  hidden_cases_ref VARCHAR(512) NOT NULL,
  time_limit_ms INTEGER NOT NULL,
  memory_limit_kb INTEGER NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT algorithm_problem_difficulty_check
    CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
  CONSTRAINT algorithm_problem_limits_check
    CHECK (time_limit_ms > 0 AND memory_limit_kb > 0)
);

CREATE TABLE sandbox_executions (
  id VARCHAR(36) PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  turn_id BIGINT NOT NULL,
  submission_seq INTEGER NOT NULL,
  problem_id VARCHAR(64) NOT NULL,
  language VARCHAR(16) NOT NULL,
  code_ref VARCHAR(512) NOT NULL,
  code_hash CHAR(64) NOT NULL,
  run_mode VARCHAR(16) NOT NULL,
  verdict VARCHAR(16),
  passed INTEGER,
  total INTEGER,
  time_ms BIGINT,
  memory_kb BIGINT,
  first_failed_case INTEGER,
  status VARCHAR(24) NOT NULL,
  superseded_by VARCHAR(36),
  pending_rejudge BOOLEAN NOT NULL DEFAULT FALSE,
  retry_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL,
  started_at TIMESTAMP(6),
  finished_at TIMESTAMP(6),
  CONSTRAINT fk_sandbox_execution_session
    FOREIGN KEY (session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_sandbox_execution_turn
    FOREIGN KEY (turn_id) REFERENCES agent_turns(id) ON DELETE CASCADE,
  CONSTRAINT fk_sandbox_execution_problem
    FOREIGN KEY (problem_id) REFERENCES algorithm_problems(id),
  CONSTRAINT fk_sandbox_execution_superseded
    FOREIGN KEY (superseded_by) REFERENCES sandbox_executions(id),
  CONSTRAINT uk_sandbox_execution_session_seq
    UNIQUE (session_id, submission_seq),
  CONSTRAINT sandbox_execution_language_check
    CHECK (language IN ('JAVA', 'PYTHON', 'CPP')),
  CONSTRAINT sandbox_execution_run_mode_check
    CHECK (run_mode IN ('SAMPLE', 'FULL')),
  CONSTRAINT sandbox_execution_verdict_check
    CHECK (verdict IS NULL OR verdict IN ('AC', 'WA', 'CE', 'TLE', 'MLE', 'RE', 'IE')),
  CONSTRAINT sandbox_execution_status_check
    CHECK (status IN ('PENDING', 'RUNNING', 'DONE', 'TIMEOUT_QUEUED')),
  CONSTRAINT sandbox_execution_counts_check
    CHECK (passed IS NULL OR (passed >= 0 AND total >= passed)),
  CONSTRAINT sandbox_execution_retry_check
    CHECK (retry_count BETWEEN 0 AND 1)
);

CREATE INDEX idx_sandbox_executions_session_created
  ON sandbox_executions (session_id, created_at);

CREATE INDEX idx_sandbox_executions_status_created
  ON sandbox_executions (status, created_at);

CREATE TABLE sandbox_execution_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  execution_id VARCHAR(36) NOT NULL,
  log_type VARCHAR(24) NOT NULL,
  storage_ref VARCHAR(512) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_sandbox_execution_log_execution
    FOREIGN KEY (execution_id) REFERENCES sandbox_executions(id) ON DELETE CASCADE,
  CONSTRAINT uk_sandbox_execution_log_type
    UNIQUE (execution_id, log_type),
  CONSTRAINT sandbox_execution_log_type_check
    CHECK (log_type IN ('COMPILE', 'TEST_CASES', 'RESOURCE_USAGE'))
);
