ALTER TABLE agent_turns
  ADD COLUMN parent_turn_index INTEGER,
  ADD COLUMN trigger_type VARCHAR(24) NOT NULL DEFAULT 'PLANNED',
  ADD COLUMN source_assessment_id BIGINT,
  ADD COLUMN source_tool_result_event_id BIGINT;

ALTER TABLE agent_turns
  ADD CONSTRAINT fk_agent_turn_parent
    FOREIGN KEY (session_id, parent_turn_index)
    REFERENCES agent_turns(session_id, turn_index),
  ADD CONSTRAINT fk_agent_turn_source_assessment
    FOREIGN KEY (source_assessment_id) REFERENCES agent_assessments(id),
  ADD CONSTRAINT fk_agent_turn_source_tool_result
    FOREIGN KEY (source_tool_result_event_id) REFERENCES agent_tool_result_events(id),
  ADD CONSTRAINT agent_turn_trigger_check CHECK (
    (trigger_type = 'PLANNED'
      AND parent_turn_index IS NULL
      AND source_assessment_id IS NULL
      AND source_tool_result_event_id IS NULL)
    OR
    (trigger_type = 'ASSESSMENT_GAP'
      AND parent_turn_index IS NOT NULL
      AND source_assessment_id IS NOT NULL
      AND source_tool_result_event_id IS NULL)
    OR
    (trigger_type = 'TOOL_RESULT'
      AND parent_turn_index IS NOT NULL
      AND source_assessment_id IS NULL
      AND source_tool_result_event_id IS NOT NULL)
  );

CREATE TABLE agent_assessment_probe_gaps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  gap_order INTEGER NOT NULL,
  gap_code VARCHAR(32) NOT NULL,
  anchor TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_assessment_probe_gap_assessment
    FOREIGN KEY (assessment_id) REFERENCES agent_assessments(id) ON DELETE CASCADE,
  CONSTRAINT uk_assessment_probe_gap_order UNIQUE (assessment_id, gap_order),
  CONSTRAINT assessment_probe_gap_order_check CHECK (gap_order > 0)
);

CREATE TABLE candidate_memory_episode_facts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  session_id VARCHAR(36) NOT NULL,
  session_mode VARCHAR(16) NOT NULL,
  turn_id BIGINT NOT NULL,
  turn_index INTEGER NOT NULL,
  assessment_id BIGINT NOT NULL,
  skill_id VARCHAR(64) NOT NULL,
  focus_id VARCHAR(64) NOT NULL,
  target_id VARCHAR(36) NOT NULL,
  work_revision_before BIGINT NOT NULL,
  work_revision_after BIGINT NOT NULL,
  assistance_level VARCHAR(16) NOT NULL,
  closure_status VARCHAR(16) NOT NULL,
  corrects_episode_id BIGINT,
  enrichment_status VARCHAR(24) NOT NULL,
  enrichment_error TEXT,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_memory_episode_turn
    FOREIGN KEY (turn_id) REFERENCES agent_turns(id) ON DELETE CASCADE,
  CONSTRAINT fk_memory_episode_assessment
    FOREIGN KEY (assessment_id) REFERENCES agent_assessments(id),
  CONSTRAINT fk_memory_episode_correction
    FOREIGN KEY (corrects_episode_id) REFERENCES candidate_memory_episode_facts(id),
  CONSTRAINT uk_memory_episode_session_turn UNIQUE (session_id, turn_index),
  CONSTRAINT uk_memory_episode_turn_id UNIQUE (turn_id),
  CONSTRAINT memory_episode_mode_check
    CHECK (session_mode IN ('EVALUATION', 'PRACTICE')),
  CONSTRAINT memory_episode_assistance_check
    CHECK (assistance_level IN ('NONE', 'FOLLOW_UP', 'HINT', 'TOOL_ASSISTED')),
  CONSTRAINT memory_episode_closure_check
    CHECK (closure_status IN ('RESOLVED', 'UNRESOLVED', 'ABANDONED')),
  CONSTRAINT memory_episode_revision_check
    CHECK (work_revision_before > 0 AND work_revision_after > work_revision_before),
  CONSTRAINT memory_episode_enrichment_status_check CHECK (
    enrichment_status IN (
      'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'
    )
  )
);

CREATE INDEX idx_memory_episode_owner_topic_created
  ON candidate_memory_episode_facts (
    tenant_id, candidate_id, skill_id, focus_id, created_at DESC, id DESC
  );

CREATE TABLE agent_question_exposures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  session_id VARCHAR(36) NOT NULL,
  turn_id BIGINT NOT NULL,
  skill_id VARCHAR(64) NOT NULL,
  focus_id VARCHAR(64) NOT NULL,
  evidence_objective VARCHAR(500) NOT NULL,
  probe_depth VARCHAR(8) NOT NULL,
  difficulty VARCHAR(32) NOT NULL,
  question_text TEXT NOT NULL,
  scenario_fingerprint VARCHAR(64) NOT NULL,
  wording_fingerprint VARCHAR(64) NOT NULL,
  source_exposure_id BIGINT,
  source_episode_id BIGINT,
  embedding_document_id VARCHAR(80) NOT NULL,
  asked_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_question_exposure_turn
    FOREIGN KEY (turn_id) REFERENCES agent_turns(id) ON DELETE CASCADE,
  CONSTRAINT fk_question_exposure_source
    FOREIGN KEY (source_exposure_id) REFERENCES agent_question_exposures(id),
  CONSTRAINT fk_question_exposure_episode
    FOREIGN KEY (source_episode_id) REFERENCES candidate_memory_episode_facts(id),
  CONSTRAINT uk_question_exposure_turn UNIQUE (turn_id),
  CONSTRAINT uk_question_exposure_document UNIQUE (embedding_document_id),
  CONSTRAINT question_exposure_depth_check
    CHECK (probe_depth IN ('L0', 'L1', 'L2', 'L3', 'L4'))
);

CREATE INDEX idx_question_exposure_owner_topic_asked
  ON agent_question_exposures (
    tenant_id, candidate_id, skill_id, focus_id, asked_at DESC, id DESC
  );

CREATE TABLE candidate_semantic_contributions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  episode_id BIGINT NOT NULL,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  skill_id VARCHAR(64) NOT NULL,
  focus_id VARCHAR(64) NOT NULL,
  track VARCHAR(24) NOT NULL,
  evaluation_level VARCHAR(2),
  practice_outcome VARCHAR(16),
  assistance_level VARCHAR(16),
  target_depth VARCHAR(2),
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_semantic_contribution_episode
    FOREIGN KEY (episode_id) REFERENCES candidate_memory_episode_facts(id),
  CONSTRAINT uk_semantic_contribution_episode_track UNIQUE (episode_id, track),
  CONSTRAINT semantic_contribution_track_fields_check CHECK (
    (track = 'EVALUATED_CAPABILITY'
      AND evaluation_level IS NOT NULL
      AND practice_outcome IS NULL
      AND assistance_level IS NULL
      AND target_depth IS NULL)
    OR
    (track = 'PRACTICE_MASTERY'
      AND evaluation_level IS NULL
      AND practice_outcome IS NOT NULL
      AND assistance_level IS NOT NULL
      AND target_depth IS NOT NULL)
  )
);

CREATE INDEX idx_semantic_contribution_owner_topic_created
  ON candidate_semantic_contributions (
    tenant_id, candidate_id, skill_id, focus_id, created_at, id
  );

CREATE TABLE candidate_semantic_states (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  skill_id VARCHAR(64) NOT NULL,
  focus_id VARCHAR(64) NOT NULL,
  track VARCHAR(24) NOT NULL,
  revision BIGINT NOT NULL,
  l0_count BIGINT NOT NULL DEFAULT 0,
  l1_count BIGINT NOT NULL DEFAULT 0,
  l2_count BIGINT NOT NULL DEFAULT 0,
  l3_count BIGINT NOT NULL DEFAULT 0,
  l4_count BIGINT NOT NULL DEFAULT 0,
  none_count BIGINT NOT NULL DEFAULT 0,
  follow_up_count BIGINT NOT NULL DEFAULT 0,
  hint_count BIGINT NOT NULL DEFAULT 0,
  tool_assisted_count BIGINT NOT NULL DEFAULT 0,
  unresolved_count BIGINT NOT NULL DEFAULT 0,
  evaluated_ability VARCHAR(16),
  practice_mastery VARCHAR(16),
  latest_practice_outcome VARCHAR(16),
  latest_assistance_level VARCHAR(16),
  latest_target_depth VARCHAR(2),
  latest_practice_episode_id BIGINT,
  latest_practice_at TIMESTAMP(6),
  stable_patterns TEXT NOT NULL,
  transfer_status VARCHAR(24),
  confirmed_by_episode_id BIGINT,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT semantic_state_non_negative_check CHECK (
    l0_count >= 0 AND l1_count >= 0 AND l2_count >= 0
      AND l3_count >= 0 AND l4_count >= 0 AND none_count >= 0
      AND follow_up_count >= 0 AND hint_count >= 0
      AND tool_assisted_count >= 0 AND unresolved_count >= 0
  ),
  CONSTRAINT semantic_state_track_fields_check CHECK (
    (track = 'EVALUATED_CAPABILITY'
      AND evaluated_ability IS NOT NULL
      AND practice_mastery IS NULL
      AND transfer_status IS NULL)
    OR
    (track = 'PRACTICE_MASTERY'
      AND evaluated_ability IS NULL
      AND practice_mastery IS NOT NULL
      AND transfer_status IS NOT NULL)
  )
);

CREATE UNIQUE INDEX uk_semantic_state_owner_topic_track
  ON candidate_semantic_states (
    tenant_id, candidate_id, skill_id, focus_id, track
  ) NULLS NOT DISTINCT;
