CREATE TABLE agent_tool_calls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invocation_id VARCHAR(64) NOT NULL,
  session_id VARCHAR(36) NOT NULL,
  turn_index INTEGER NOT NULL,
  role VARCHAR(32) NOT NULL,
  tool_name VARCHAR(64) NOT NULL,
  decision_reason VARCHAR(500) NOT NULL,
  input_summary VARCHAR(500) NOT NULL,
  output_summary VARCHAR(500) NOT NULL,
  result_id VARCHAR(500) NOT NULL,
  duration_ms BIGINT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT uk_agent_tool_call_invocation UNIQUE (invocation_id),
  CONSTRAINT fk_agent_tool_call_turn
    FOREIGN KEY (session_id, turn_index)
    REFERENCES agent_turns(session_id, turn_index) ON DELETE CASCADE
);

CREATE INDEX idx_agent_tool_calls_session_turn
  ON agent_tool_calls (session_id, turn_index);
