CREATE TABLE dimension_briefs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  dimension_order INTEGER NOT NULL,
  dimension VARCHAR(100) NOT NULL,
  focus VARCHAR(500) NOT NULL,
  key_findings TEXT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_dimension_brief_plan
    FOREIGN KEY (session_id, dimension_order)
    REFERENCES agent_plans(session_id, dimension_order) ON DELETE CASCADE,
  CONSTRAINT uk_dimension_brief_session_order
    UNIQUE (session_id, dimension_order)
);

CREATE TABLE dimension_brief_turn_refs (
  brief_id BIGINT NOT NULL,
  reference_order INTEGER NOT NULL,
  turn_index INTEGER NOT NULL,
  CONSTRAINT pk_dimension_brief_turn_ref
    PRIMARY KEY (brief_id, reference_order),
  CONSTRAINT fk_dimension_brief_turn_ref_brief
    FOREIGN KEY (brief_id) REFERENCES dimension_briefs(id) ON DELETE CASCADE
);
