CREATE TABLE project_repos (
  id VARCHAR(36) PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  tenant_id VARCHAR(64),
  repository_ref VARCHAR(512) NOT NULL,
  commit_hash VARCHAR(64) NOT NULL,
  expires_at TIMESTAMP(6) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_project_repo_session
    FOREIGN KEY (session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT uk_project_repo_session_commit UNIQUE (session_id, commit_hash)
);

CREATE INDEX idx_project_repos_expiry ON project_repos (expires_at);

CREATE TABLE analysis_jobs (
  id VARCHAR(36) PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  repository_id VARCHAR(36) NOT NULL,
  status VARCHAR(16) NOT NULL,
  duration_ms BIGINT,
  token_cost BIGINT,
  failure_reason VARCHAR(200),
  created_at TIMESTAMP(6) NOT NULL,
  started_at TIMESTAMP(6),
  finished_at TIMESTAMP(6),
  CONSTRAINT fk_analysis_job_session
    FOREIGN KEY (session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_analysis_job_repository
    FOREIGN KEY (repository_id) REFERENCES project_repos(id) ON DELETE CASCADE,
  CONSTRAINT analysis_job_status_check
    CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'TIMED_OUT'))
);

CREATE INDEX idx_analysis_jobs_repository_created
  ON analysis_jobs (repository_id, created_at DESC);

CREATE TABLE project_digests (
  id VARCHAR(64) PRIMARY KEY,
  repository_id VARCHAR(36) NOT NULL UNIQUE,
  commit_hash VARCHAR(64) NOT NULL,
  payload_json TEXT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_project_digest_repository
    FOREIGN KEY (repository_id) REFERENCES project_repos(id) ON DELETE CASCADE
);

CREATE TABLE claim_verifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id VARCHAR(36) NOT NULL,
  claim_id VARCHAR(64) NOT NULL,
  payload_json TEXT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_claim_verification_repository
    FOREIGN KEY (repository_id) REFERENCES project_repos(id) ON DELETE CASCADE,
  CONSTRAINT uk_claim_verification_repo_claim UNIQUE (repository_id, claim_id)
);

CREATE TABLE scenario_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id VARCHAR(36) NOT NULL,
  scenario_id VARCHAR(64) NOT NULL,
  payload_json TEXT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_scenario_card_repository
    FOREIGN KEY (repository_id) REFERENCES project_repos(id) ON DELETE CASCADE,
  CONSTRAINT uk_scenario_card_repo_scenario UNIQUE (repository_id, scenario_id)
);
