CREATE TABLE agent_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  dimension_order INTEGER NOT NULL,
  dimension VARCHAR(100) NOT NULL,
  focus VARCHAR(500) NOT NULL,
  suggested_turns INTEGER NOT NULL,
  allocated_turns INTEGER NOT NULL,
  expected_depth VARCHAR(8) NOT NULL,
  depth_ceiling VARCHAR(8) NOT NULL,
  follow_up_budget INTEGER NOT NULL,
  tool_budget INTEGER NOT NULL,
  evidence_objectives_json TEXT NOT NULL,
  completed_turns INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_agent_plan_session
    FOREIGN KEY (session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT uk_agent_plan_session_order
    UNIQUE (session_id, dimension_order),
  CONSTRAINT agent_plan_status_check
    CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED')),
  CONSTRAINT agent_plan_depth_check
    CHECK (
      expected_depth IN ('L0', 'L1', 'L2', 'L3', 'L4')
      AND depth_ceiling IN ('L0', 'L1', 'L2', 'L3', 'L4')
    ),
  CONSTRAINT agent_plan_turns_check
    CHECK (
      suggested_turns BETWEEN 1 AND 12
      AND allocated_turns BETWEEN 1 AND 12
      AND completed_turns BETWEEN 0 AND allocated_turns
      AND follow_up_budget BETWEEN 0 AND 3
      AND tool_budget >= 0
    )
);

ALTER TABLE agent_turns
  ADD COLUMN dimension_order INTEGER;

ALTER TABLE agent_turns
  ADD CONSTRAINT fk_agent_turn_plan_dimension
  FOREIGN KEY (session_id, dimension_order)
  REFERENCES agent_plans(session_id, dimension_order);
