CREATE TABLE agent_assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  turn_index INTEGER NOT NULL,
  dimension_order INTEGER NOT NULL,
  depth_level VARCHAR(2) NOT NULL,
  confidence NUMERIC(4, 3) NOT NULL,
  rationale_summary VARCHAR(500) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_agent_assessment_turn
    FOREIGN KEY (session_id, turn_index)
    REFERENCES agent_turns(session_id, turn_index) ON DELETE CASCADE,
  CONSTRAINT fk_agent_assessment_dimension
    FOREIGN KEY (session_id, dimension_order)
    REFERENCES agent_plans(session_id, dimension_order),
  CONSTRAINT uk_agent_assessment_turn
    UNIQUE (session_id, turn_index),
  CONSTRAINT agent_assessment_depth_check
    CHECK (depth_level IN ('L0', 'L1', 'L2', 'L3', 'L4')),
  CONSTRAINT agent_assessment_confidence_check
    CHECK (confidence BETWEEN 0 AND 1)
);

CREATE INDEX idx_agent_assessments_session_dimension
  ON agent_assessments (session_id, dimension_order, turn_index);

CREATE TABLE agent_evidences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  evidence_type VARCHAR(20) NOT NULL,
  source_session_id VARCHAR(36) NOT NULL,
  source_turn_index INTEGER NOT NULL,
  quote_text TEXT,
  tool_call_id BIGINT,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_agent_evidence_assessment
    FOREIGN KEY (assessment_id) REFERENCES agent_assessments(id) ON DELETE CASCADE,
  CONSTRAINT fk_agent_evidence_turn
    FOREIGN KEY (source_session_id, source_turn_index)
    REFERENCES agent_turns(session_id, turn_index),
  CONSTRAINT fk_agent_evidence_tool_call
    FOREIGN KEY (tool_call_id) REFERENCES agent_tool_calls(id),
  CONSTRAINT agent_evidence_type_check
    CHECK (evidence_type IN ('QUOTE', 'TOOL_RESULT')),
  CONSTRAINT agent_evidence_source_check
    CHECK (
      (evidence_type = 'QUOTE' AND quote_text IS NOT NULL AND tool_call_id IS NULL)
      OR
      (evidence_type = 'TOOL_RESULT' AND quote_text IS NULL AND tool_call_id IS NOT NULL)
    )
);

CREATE INDEX idx_agent_evidences_assessment
  ON agent_evidences (assessment_id);
