ALTER TABLE candidate_ability_profiles
  RENAME TO legacy_candidate_ability_profiles;

CREATE TABLE candidate_ability_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  skill_id VARCHAR(64) NOT NULL,
  focus_id VARCHAR(64) NOT NULL,
  ability VARCHAR(16) NOT NULL,
  l0_count BIGINT NOT NULL,
  l1_count BIGINT NOT NULL,
  l2_count BIGINT NOT NULL,
  l3_count BIGINT NOT NULL,
  l4_count BIGINT NOT NULL,
  source_session_id VARCHAR(36) NOT NULL,
  revision_reason VARCHAR(24) NOT NULL,
  superseded_at TIMESTAMP(6),
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_ability_profile_snapshot_session
    FOREIGN KEY (source_session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT ability_profile_snapshot_ability_check
    CHECK (ability IN ('WEAK', 'COMPETENT', 'PROFICIENT')),
  CONSTRAINT ability_profile_snapshot_reason_check
    CHECK (revision_reason IN ('SESSION_COMPLETED', 'ASSESSMENT_CORRECTED')),
  CONSTRAINT ability_profile_snapshot_counts_check
    CHECK (l0_count >= 0 AND l1_count >= 0 AND l2_count >= 0
      AND l3_count >= 0 AND l4_count >= 0)
);

CREATE UNIQUE INDEX uk_ability_profile_current_owner_topic
  ON candidate_ability_profiles (tenant_id, candidate_id, skill_id, focus_id)
  NULLS NOT DISTINCT
  WHERE superseded_at IS NULL;

CREATE INDEX idx_ability_profile_owner_history
  ON candidate_ability_profiles (
    tenant_id, candidate_id, skill_id, focus_id, created_at DESC, id DESC
  );
