CREATE TABLE agent_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  dimension_order INTEGER NOT NULL,
  dimension VARCHAR(100) NOT NULL,
  focus VARCHAR(500) NOT NULL,
  suggested_turns INTEGER NOT NULL,
  allocated_turns INTEGER NOT NULL,
  expected_depth VARCHAR(8) NOT NULL,
  depth_ceiling VARCHAR(8) NOT NULL,
  follow_up_budget INTEGER NOT NULL,
  tool_budget INTEGER NOT NULL,
  evidence_objectives_json TEXT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_agent_plan_session
    FOREIGN KEY (session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT uk_agent_plan_session_order
    UNIQUE (session_id, dimension_order),
  CONSTRAINT agent_plan_depth_check
    CHECK (
      expected_depth IN ('L0', 'L1', 'L2', 'L3', 'L4')
      AND depth_ceiling IN ('L0', 'L1', 'L2', 'L3', 'L4')
    ),
  CONSTRAINT agent_plan_turns_check
    CHECK (
      suggested_turns BETWEEN 1 AND 12
      AND allocated_turns BETWEEN 1 AND 12
      AND follow_up_budget BETWEEN 0 AND 3
      AND tool_budget >= 0
    )
);

ALTER TABLE agent_turns
  ADD COLUMN dimension_order INTEGER;

ALTER TABLE agent_turns
  ADD CONSTRAINT fk_agent_turn_plan_dimension
  FOREIGN KEY (session_id, dimension_order)
  REFERENCES agent_plans(session_id, dimension_order);

CREATE TABLE agent_work_states (
  session_id VARCHAR(36) PRIMARY KEY,
  revision BIGINT NOT NULL,
  phase VARCHAR(24) NOT NULL,
  active_action_intent_id VARCHAR(36),
  state_json TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_work_state_session
    FOREIGN KEY (session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT work_state_phase_check
    CHECK (phase IN ('READY_TO_DECIDE', 'ACTION_PENDING', 'AWAITING_ANSWER', 'FINISHED')),
  CONSTRAINT work_state_revision_check CHECK (revision > 0)
);

CREATE TABLE agent_work_state_patches (
  patch_id VARCHAR(64) PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  base_revision BIGINT NOT NULL,
  result_revision BIGINT NOT NULL,
  source_type VARCHAR(24) NOT NULL,
  source_id VARCHAR(128) NOT NULL,
  operations_json TEXT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_work_state_patch_session
    FOREIGN KEY (session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT uk_work_state_patch_source
    UNIQUE (session_id, source_type, source_id),
  CONSTRAINT work_state_patch_revision_check
    CHECK (result_revision = base_revision + 1),
  CONSTRAINT work_state_patch_source_check
    CHECK (source_type IN ('INITIALIZATION', 'ASSESSMENT', 'TOOL_RESULT', 'POLICY', 'ACTION_RESULT'))
);
