ALTER TABLE candidate_memory_episode_facts
  ADD COLUMN answer_summary TEXT;

CREATE TABLE candidate_memory_episode_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  episode_id BIGINT NOT NULL,
  category VARCHAR(24) NOT NULL,
  tag VARCHAR(64) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_id BIGINT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_memory_episode_tag_episode
    FOREIGN KEY (episode_id) REFERENCES candidate_memory_episode_facts(id) ON DELETE CASCADE,
  CONSTRAINT uk_memory_episode_tag_source
    UNIQUE (episode_id, category, tag, source_type, source_id),
  CONSTRAINT memory_episode_tag_category_check
    CHECK (category IN ('ERROR_PATTERN', 'ANSWER_HABIT')),
  CONSTRAINT memory_episode_tag_source_check
    CHECK (source_type IN ('ASSESSMENT_EVIDENCE', 'PROBE_GAP', 'TOOL_RESULT'))
);

CREATE INDEX idx_memory_episode_tags_episode
  ON candidate_memory_episode_tags (episode_id, category, tag);
