CREATE TABLE agent_interview_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  runtime_version VARCHAR(32) NOT NULL,
  jd TEXT NOT NULL,
  resume TEXT NOT NULL,
  current_turn INTEGER NOT NULL,
  max_turns INTEGER NOT NULL,
  selected_skill_id VARCHAR(64),
  selected_skill_name VARCHAR(255),
  selected_skill_description TEXT,
  selected_skill_body TEXT,
  selected_skill_hash VARCHAR(64),
  turns_json TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  finish_reason VARCHAR(500),
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  completed_at TIMESTAMP(6),
  version BIGINT,
  CONSTRAINT uk_agent_interview_session_id UNIQUE (session_id),
  CONSTRAINT agent_interview_status_check
    CHECK (status IN ('CREATED', 'IN_PROGRESS', 'COMPLETED', 'FAILED')),
  CONSTRAINT agent_interview_turn_bounds_check
    CHECK (current_turn >= 0 AND current_turn <= max_turns AND max_turns <= 6)
);

CREATE INDEX idx_agent_interview_status_created
  ON agent_interview_sessions (status, created_at);
