ALTER TABLE agent_turns
  ADD COLUMN parent_turn_index INTEGER,
  ADD COLUMN trigger_type VARCHAR(24) NOT NULL DEFAULT 'PLANNED',
  ADD COLUMN source_assessment_id BIGINT,
  ADD COLUMN source_tool_result_event_id BIGINT;

ALTER TABLE agent_turns
  ADD CONSTRAINT fk_agent_turn_parent
    FOREIGN KEY (session_id, parent_turn_index)
    REFERENCES agent_turns(session_id, turn_index),
  ADD CONSTRAINT fk_agent_turn_source_assessment
    FOREIGN KEY (source_assessment_id) REFERENCES agent_assessments(id),
  ADD CONSTRAINT fk_agent_turn_source_tool_result
    FOREIGN KEY (source_tool_result_event_id) REFERENCES agent_tool_result_events(id),
  ADD CONSTRAINT agent_turn_trigger_check CHECK (
    (trigger_type = 'PLANNED'
      AND parent_turn_index IS NULL
      AND source_assessment_id IS NULL
      AND source_tool_result_event_id IS NULL)
    OR
    (trigger_type = 'ASSESSMENT_GAP'
      AND parent_turn_index IS NOT NULL
      AND source_assessment_id IS NOT NULL
      AND source_tool_result_event_id IS NULL)
    OR
    (trigger_type = 'TOOL_RESULT'
      AND parent_turn_index IS NOT NULL
      AND source_assessment_id IS NULL
      AND source_tool_result_event_id IS NOT NULL)
  );

CREATE TABLE agent_assessment_probe_gaps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  gap_order INTEGER NOT NULL,
  gap_code VARCHAR(32) NOT NULL,
  anchor TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_assessment_probe_gap_assessment
    FOREIGN KEY (assessment_id) REFERENCES agent_assessments(id) ON DELETE CASCADE,
  CONSTRAINT uk_assessment_probe_gap_order UNIQUE (assessment_id, gap_order),
  CONSTRAINT assessment_probe_gap_order_check CHECK (gap_order > 0)
);

CREATE TABLE candidate_memory_episode_facts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  session_id VARCHAR(36) NOT NULL,
  turn_index INTEGER NOT NULL,
  assessment_id BIGINT NOT NULL,
  skill_id VARCHAR(64) NOT NULL,
  focus_id VARCHAR(64) NOT NULL,
  enrichment_status VARCHAR(24) NOT NULL,
  enrichment_error TEXT,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_memory_episode_turn
    FOREIGN KEY (session_id, turn_index)
    REFERENCES agent_turns(session_id, turn_index) ON DELETE CASCADE,
  CONSTRAINT fk_memory_episode_assessment
    FOREIGN KEY (assessment_id) REFERENCES agent_assessments(id),
  CONSTRAINT uk_memory_episode_session_turn UNIQUE (session_id, turn_index),
  CONSTRAINT memory_episode_enrichment_status_check CHECK (
    enrichment_status IN (
      'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'LEGACY_UNENRICHED'
    )
  )
);

CREATE INDEX idx_memory_episode_owner_topic_created
  ON candidate_memory_episode_facts (
    tenant_id, candidate_id, skill_id, focus_id, created_at DESC, id DESC
  );

CREATE TABLE candidate_ability_counters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  skill_id VARCHAR(64) NOT NULL,
  focus_id VARCHAR(64) NOT NULL,
  l0_count BIGINT NOT NULL DEFAULT 0,
  l1_count BIGINT NOT NULL DEFAULT 0,
  l2_count BIGINT NOT NULL DEFAULT 0,
  l3_count BIGINT NOT NULL DEFAULT 0,
  l4_count BIGINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT ability_counter_non_negative_check CHECK (
    l0_count >= 0 AND l1_count >= 0 AND l2_count >= 0
      AND l3_count >= 0 AND l4_count >= 0
  )
);

CREATE UNIQUE INDEX uk_ability_counter_owner_topic
  ON candidate_ability_counters (
    tenant_id, candidate_id, skill_id, focus_id
  ) NULLS NOT DISTINCT;
