ALTER TABLE agent_sessions
  ADD COLUMN candidate_id VARCHAR(64) NOT NULL;

ALTER TABLE agent_plans
  ADD COLUMN focus_id VARCHAR(64) NOT NULL;

CREATE TABLE candidate_memory_topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id VARCHAR(64) NOT NULL,
  skill_id VARCHAR(64) NOT NULL,
  focus_id VARCHAR(64) NOT NULL,
  source_session_id VARCHAR(36) NOT NULL,
  dimension_order INTEGER NOT NULL,
  observed_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_candidate_memory_topic_session
    FOREIGN KEY (source_session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_candidate_memory_topic_dimension
    FOREIGN KEY (source_session_id, dimension_order)
    REFERENCES agent_plans(session_id, dimension_order),
  CONSTRAINT uk_candidate_memory_topic_source
    UNIQUE (source_session_id, dimension_order)
);

CREATE INDEX idx_candidate_memory_topics_candidate_observed
  ON candidate_memory_topics (candidate_id, observed_at DESC);
