CREATE TABLE candidate_ability_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  dimension VARCHAR(100) NOT NULL,
  dimension_order INTEGER NOT NULL,
  depth_level VARCHAR(2) NOT NULL,
  source_session_id VARCHAR(36) NOT NULL,
  source_assessment_id BIGINT NOT NULL,
  superseded_by BIGINT,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_candidate_ability_profile_session
    FOREIGN KEY (source_session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_candidate_ability_profile_assessment
    FOREIGN KEY (source_assessment_id) REFERENCES agent_assessments(id) ON DELETE CASCADE,
  CONSTRAINT fk_candidate_ability_profile_superseded
    FOREIGN KEY (superseded_by) REFERENCES candidate_ability_profiles(id),
  CONSTRAINT uk_candidate_ability_profile_session_dimension
    UNIQUE (source_session_id, dimension_order),
  CONSTRAINT candidate_ability_profile_depth_check
    CHECK (depth_level IN ('L0', 'L1', 'L2', 'L3', 'L4'))
);

CREATE INDEX idx_candidate_ability_profile_current
  ON candidate_ability_profiles (tenant_id, candidate_id, dimension, superseded_by);
