CREATE TABLE practice_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  source_session_id VARCHAR(36) NOT NULL,
  dimension_order INTEGER NOT NULL,
  dimension VARCHAR(100) NOT NULL,
  demonstrated_depth VARCHAR(2) NOT NULL,
  question_source_id VARCHAR(128) NOT NULL,
  question_difficulty VARCHAR(16) NOT NULL,
  question TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_practice_record_session
    FOREIGN KEY (source_session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT uk_practice_record_session_dimension
    UNIQUE (source_session_id, dimension_order),
  CONSTRAINT practice_record_depth_check
    CHECK (demonstrated_depth IN ('L0', 'L1', 'L2', 'L3', 'L4')),
  CONSTRAINT practice_record_status_check
    CHECK (status IN ('PENDING', 'COMPLETED'))
);

CREATE INDEX idx_practice_records_candidate
  ON practice_records (tenant_id, candidate_id, status, created_at);
