CREATE TABLE agent_sessions (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  completed_at TIMESTAMP(6),
  CONSTRAINT agent_sessions_status_check
    CHECK (status IN ('CREATED', 'IN_PROGRESS', 'COMPLETED', 'FAILED'))
);

CREATE TABLE agent_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  dimension_order INTEGER NOT NULL,
  dimension VARCHAR(100) NOT NULL,
  focus VARCHAR(500) NOT NULL,
  suggested_skill VARCHAR(64),
  focus_id VARCHAR(64),
  CONSTRAINT fk_agent_plan_session
    FOREIGN KEY (session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT uk_agent_plan_session_order
    UNIQUE (session_id, dimension_order)
);

CREATE TABLE agent_turns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  turn_index INTEGER NOT NULL,
  dimension_order INTEGER,
  question TEXT NOT NULL,
  answer TEXT,
  created_at TIMESTAMP(6) NOT NULL,
  answered_at TIMESTAMP(6),
  CONSTRAINT fk_agent_turn_session
    FOREIGN KEY (session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_agent_turn_plan_dimension
    FOREIGN KEY (session_id, dimension_order)
    REFERENCES agent_plans(session_id, dimension_order),
  CONSTRAINT uk_agent_turn_session_index
    UNIQUE (session_id, turn_index)
);

CREATE TABLE agent_assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  turn_index INTEGER NOT NULL,
  dimension_order INTEGER NOT NULL,
  depth_level VARCHAR(2) NOT NULL,
  confidence NUMERIC(4, 3) NOT NULL,
  rationale_summary VARCHAR(500) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_agent_assessment_turn
    FOREIGN KEY (session_id, turn_index)
    REFERENCES agent_turns(session_id, turn_index) ON DELETE CASCADE,
  CONSTRAINT fk_agent_assessment_dimension
    FOREIGN KEY (session_id, dimension_order)
    REFERENCES agent_plans(session_id, dimension_order),
  CONSTRAINT uk_agent_assessment_turn
    UNIQUE (session_id, turn_index),
  CONSTRAINT agent_assessment_depth_check
    CHECK (depth_level IN ('L0', 'L1', 'L2', 'L3', 'L4')),
  CONSTRAINT agent_assessment_confidence_check
    CHECK (confidence BETWEEN 0 AND 1)
);

CREATE TABLE agent_tool_result_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE candidate_ability_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  dimension VARCHAR(100) NOT NULL,
  dimension_order INTEGER NOT NULL,
  depth_level VARCHAR(2) NOT NULL,
  source_session_id VARCHAR(36) NOT NULL,
  source_assessment_id BIGINT NOT NULL,
  superseded_by BIGINT,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_candidate_ability_profile_session
    FOREIGN KEY (source_session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_candidate_ability_profile_assessment
    FOREIGN KEY (source_assessment_id) REFERENCES agent_assessments(id) ON DELETE CASCADE,
  CONSTRAINT fk_candidate_ability_profile_superseded
    FOREIGN KEY (superseded_by) REFERENCES candidate_ability_profiles(id),
  CONSTRAINT uk_candidate_ability_profile_session_dimension
    UNIQUE (source_session_id, dimension_order),
  CONSTRAINT candidate_ability_profile_depth_check
    CHECK (depth_level IN ('L0', 'L1', 'L2', 'L3', 'L4'))
);
