package interview.guide.modules.interview.agent.adaptive.algorithm;

import java.time.LocalDateTime;

public record SandboxExecution(
    String id,
    String sessionId,
    long turnId,
    int submissionSeq,
    SandboxWorkloadType workloadType,
    String problemId,
    String scenarioId,
    String workspaceRef,
    String testsRef,
    SandboxLanguage language,
    String codeRef,
    String codeHash,
    SandboxRunMode runMode,
    SandboxExecutionStatus status,
    SandboxVerdict verdict,
    Integer passed,
    Integer total,
    Long timeMs,
    Long memoryKb,
    Integer firstFailedCase,
    String supersededBy,
    boolean pendingRejudge,
    int retryCount,
    LocalDateTime createdAt,
    LocalDateTime finishedAt,
    SandboxPolicyViolation policyViolation
) {

  public SandboxExecution(
      String id,
      String sessionId,
      long turnId,
      int submissionSeq,
      String problemId,
      SandboxLanguage language,
      String codeRef,
      String codeHash,
      SandboxRunMode runMode,
      SandboxExecutionStatus status,
      SandboxVerdict verdict,
      Integer passed,
      Integer total,
      Long timeMs,
      Long memoryKb,
      Integer firstFailedCase,
      String supersededBy,
      boolean pendingRejudge,
      int retryCount,
      LocalDateTime createdAt,
      LocalDateTime finishedAt
  ) {
    this(
        id,
        sessionId,
        turnId,
        submissionSeq,
        SandboxWorkloadType.ALGORITHM,
        problemId,
        null,
        null,
        null,
        language,
        codeRef,
        codeHash,
        runMode,
        status,
        verdict,
        passed,
        total,
        timeMs,
        memoryKb,
        firstFailedCase,
        supersededBy,
        pendingRejudge,
        retryCount,
        createdAt,
        finishedAt,
        null
    );
  }
}
