package interview.guide.modules.interview.agent.adaptive.memory.episode;

public enum AnswerHabit {
  CONCLUSION_WITHOUT_EVIDENCE,
  EXAMPLE_WITHOUT_METRICS,
  IMPLEMENTATION_WITHOUT_TRADEOFF,
  VAGUE_PERSONAL_OWNERSHIP,
  OVERLY_ABSOLUTE_LANGUAGE,
  STRUCTURED_REASONING,
  SELF_CORRECTS_AFTER_PROBE,
  EXPLICIT_BOUNDARY_ANALYSIS
}
