package interview.guide.modules.interview.agent.adaptive.memory.episode;

public enum ErrorPattern {
  MISSING_FAILURE_BOUNDARY,
  MISSING_CONCURRENCY_ANALYSIS,
  MISSING_CONSISTENCY_ANALYSIS,
  UNSUPPORTED_ASSUMPTION,
  CONFUSES_CONCEPTS,
  IGNORES_COMPLEXITY_COST,
  INCOMPLETE_CORRECTNESS_ARGUMENT,
  OVERGENERALIZES_SOLUTION
}
