CREATE TABLE agent_sessions (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL
);

CREATE TABLE agent_plans (
  session_id VARCHAR(36) NOT NULL,
  dimension_order INTEGER NOT NULL,
  dimension VARCHAR(100) NOT NULL,
  focus VARCHAR(500) NOT NULL,
  suggested_skill VARCHAR(64),
  focus_id VARCHAR(64),
  PRIMARY KEY (session_id, dimension_order)
);

CREATE TABLE agent_turns (
  session_id VARCHAR(36) NOT NULL,
  turn_index INTEGER NOT NULL,
  answer TEXT,
  answered_at TIMESTAMP(6),
  created_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (session_id, turn_index)
);

CREATE TABLE agent_assessments (
  id BIGINT PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  turn_index INTEGER NOT NULL,
  dimension_order INTEGER NOT NULL,
  depth_level VARCHAR(2) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  UNIQUE (session_id, turn_index)
);

CREATE TABLE legacy_candidate_ability_profiles (
  id BIGINT PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  dimension VARCHAR(100) NOT NULL,
  dimension_order INTEGER NOT NULL,
  depth_level VARCHAR(2) NOT NULL,
  source_session_id VARCHAR(36) NOT NULL,
  source_assessment_id BIGINT NOT NULL,
  superseded_by BIGINT,
  created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE candidate_memory_episode_facts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  session_id VARCHAR(36) NOT NULL,
  turn_index INTEGER NOT NULL,
  assessment_id BIGINT NOT NULL,
  skill_id VARCHAR(64) NOT NULL,
  focus_id VARCHAR(64) NOT NULL,
  enrichment_status VARCHAR(24) NOT NULL,
  enrichment_error TEXT,
  version BIGINT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  UNIQUE (session_id, turn_index)
);

CREATE TABLE candidate_ability_counters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  skill_id VARCHAR(64) NOT NULL,
  focus_id VARCHAR(64) NOT NULL,
  l0_count BIGINT NOT NULL,
  l1_count BIGINT NOT NULL,
  l2_count BIGINT NOT NULL,
  l3_count BIGINT NOT NULL,
  l4_count BIGINT NOT NULL,
  version BIGINT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE candidate_ability_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64),
  candidate_id VARCHAR(64) NOT NULL,
  skill_id VARCHAR(64) NOT NULL,
  focus_id VARCHAR(64) NOT NULL,
  ability VARCHAR(16) NOT NULL,
  l0_count BIGINT NOT NULL,
  l1_count BIGINT NOT NULL,
  l2_count BIGINT NOT NULL,
  l3_count BIGINT NOT NULL,
  l4_count BIGINT NOT NULL,
  source_session_id VARCHAR(36) NOT NULL,
  revision_reason VARCHAR(24) NOT NULL,
  superseded_at TIMESTAMP(6),
  created_at TIMESTAMP(6) NOT NULL
);
