package interview.guide.modules.interview.agent.adaptive.persistence.memory;

import static org.assertj.core.api.Assertions.assertThat;

import interview.guide.modules.interview.agent.adaptive.core.context.DepthLevel;
import interview.guide.modules.interview.agent.adaptive.core.context.MemoryOwner;
import interview.guide.modules.interview.agent.adaptive.core.context.TopicKey;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.Callable;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.FutureTask;
import java.util.concurrent.TimeUnit;
import javax.sql.DataSource;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.support.TransactionTemplate;

@EnabledIfEnvironmentVariable(
    named = "MEMORY_MIGRATION_PG_JDBC_URL",
    matches = "jdbc:postgresql:.+"
)
@EnabledIfEnvironmentVariable(named = "MEMORY_MIGRATION_PG_USER", matches = ".+")
@EnabledIfEnvironmentVariable(named = "MEMORY_MIGRATION_PG_PASSWORD", matches = ".*")
class AbilityCounterPostgresConcurrencyIntegrationTest {

  private static final int CONCURRENT_WRITES = 2;
  private static final int AWAIT_SECONDS = 5;
  private static final MemoryOwner OWNER = new MemoryOwner(null, "counter-first-create");
  private static final TopicKey TOPIC = new TopicKey("java-backend", "CONCURRENCY");

  @Test
  @DisplayName("PostgreSQL 并发首次写入同一 owner 主题时原子合并为一个 Counter")
  void shouldAtomicallyUpsertConcurrentFirstCounter() throws Exception {
    DataSource adminDataSource = adminDataSource();
    String schema = "ability_counter_" + UUID.randomUUID().toString().replace("-", "");
    JdbcTemplate adminJdbc = new JdbcTemplate(adminDataSource);
    adminJdbc.execute("CREATE SCHEMA " + schema);
    try {
      DataSource dataSource = scopedDataSource(schema);
      createCounterTable(new JdbcTemplate(dataSource));
      executeConcurrentFirstWrites(dataSource);
      assertMergedCounter(new JdbcTemplate(dataSource));
    } finally {
      adminJdbc.execute("DROP SCHEMA " + schema + " CASCADE");
    }
  }

  private void executeConcurrentFirstWrites(DataSource dataSource) throws Exception {
    var store = new JdbcAbilityCounterIncrementStore(dataSource);
    var transaction = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
    CountDownLatch ready = new CountDownLatch(CONCURRENT_WRITES);
    CountDownLatch start = new CountDownLatch(1);
    CounterWriteContext context = new CounterWriteContext(
        store, transaction, ready, start
    );
    List<FutureTask<Void>> tasks = List.of(
        task(context, DepthLevel.L2),
        task(context, DepthLevel.L4)
    );
    tasks.forEach(Thread::startVirtualThread);
    assertThat(ready.await(AWAIT_SECONDS, TimeUnit.SECONDS)).isTrue();
    start.countDown();
    for (FutureTask<Void> task : tasks) {
      task.get(AWAIT_SECONDS, TimeUnit.SECONDS);
    }
  }

  private FutureTask<Void> task(
      CounterWriteContext context,
      DepthLevel level
  ) {
    Callable<Void> write = () -> {
      context.transaction().executeWithoutResult(status -> {
        context.ready().countDown();
        await(context.start());
        context.store().increment(OWNER, TOPIC, level);
      });
      return null;
    };
    return new FutureTask<>(write);
  }

  private void await(CountDownLatch latch) {
    try {
      if (!latch.await(AWAIT_SECONDS, TimeUnit.SECONDS)) {
        throw new IllegalStateException("并发 Counter 写入未按时开始");
      }
    } catch (InterruptedException exception) {
      Thread.currentThread().interrupt();
      throw new IllegalStateException("并发 Counter 写入被中断", exception);
    }
  }

  private void assertMergedCounter(JdbcTemplate jdbc) {
    Map<String, Object> counter = jdbc.queryForMap("""
        SELECT l0_count, l1_count, l2_count, l3_count, l4_count, version
        FROM candidate_ability_counters
        """);
    assertThat(jdbc.queryForObject(
        "SELECT COUNT(*) FROM candidate_ability_counters", Long.class
    )).isOne();
    assertThat(counter)
        .containsEntry("l0_count", 0L)
        .containsEntry("l1_count", 0L)
        .containsEntry("l2_count", 1L)
        .containsEntry("l3_count", 0L)
        .containsEntry("l4_count", 1L)
        .containsEntry("version", 1L);
  }

  private void createCounterTable(JdbcTemplate jdbc) {
    jdbc.execute("""
        CREATE TABLE candidate_ability_counters (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id VARCHAR(64),
          candidate_id VARCHAR(64) NOT NULL,
          skill_id VARCHAR(64) NOT NULL,
          focus_id VARCHAR(64) NOT NULL,
          l0_count BIGINT NOT NULL DEFAULT 0,
          l1_count BIGINT NOT NULL DEFAULT 0,
          l2_count BIGINT NOT NULL DEFAULT 0,
          l3_count BIGINT NOT NULL DEFAULT 0,
          l4_count BIGINT NOT NULL DEFAULT 0,
          version BIGINT NOT NULL DEFAULT 0,
          created_at TIMESTAMP(6) NOT NULL,
          updated_at TIMESTAMP(6) NOT NULL,
          CONSTRAINT ability_counter_non_negative_check CHECK (
            l0_count >= 0 AND l1_count >= 0 AND l2_count >= 0
              AND l3_count >= 0 AND l4_count >= 0
          )
        )
        """);
    jdbc.execute("""
        CREATE UNIQUE INDEX uk_ability_counter_owner_topic
          ON candidate_ability_counters (
            tenant_id, candidate_id, skill_id, focus_id
          ) NULLS NOT DISTINCT
        """);
  }

  private DataSource adminDataSource() {
    return new DriverManagerDataSource(
        System.getenv("MEMORY_MIGRATION_PG_JDBC_URL"),
        System.getenv("MEMORY_MIGRATION_PG_USER"),
        System.getenv("MEMORY_MIGRATION_PG_PASSWORD")
    );
  }

  private DataSource scopedDataSource(String schema) {
    String baseUrl = System.getenv("MEMORY_MIGRATION_PG_JDBC_URL");
    String separator = baseUrl.contains("?") ? "&" : "?";
    return new DriverManagerDataSource(
        baseUrl + separator + "currentSchema=" + schema,
        System.getenv("MEMORY_MIGRATION_PG_USER"),
        System.getenv("MEMORY_MIGRATION_PG_PASSWORD")
    );
  }

  private record CounterWriteContext(
      JdbcAbilityCounterIncrementStore store,
      TransactionTemplate transaction,
      CountDownLatch ready,
      CountDownLatch start
  ) {}
}
